AdcRead
AdcName
CircularBuffer< AdcRead::adc_reading, ADC_BUFFER_SIZE > AdcRead::adc_buffer_
Referenced by DoRead, CanCom::SendReadings.
AdcName AdcRead::adc_list_[6][6]
AdcRead::AdcRead()=default
AdcRead::adc_reading AdcRead::DoRead()
Kalder AsyncADC med et antal ADC'er på baggrund af nuværende state. Nye måling bliver lagt i CircularBuffer'en adc_buffer_.
AdcRead::adc_reading Nye måling
References adc_buffer_, adc_read_list, AsyncADC, Fsm::GetCurrentState, Fsm::LOW.
Referenced by ReadAdc.
void AdcRead::ReadU16(adc_thread_args *args)
Måler et givent antal gange på et givent device fra adc_thread_args og skriver middelværdi til adc_thread_args dest.
args adc_thread_args med AnalogIn pointer til devicet og uint16_t pointer til resultatet
References ADC_MEASURE_LOOPS, AdcRead::adc_thread_args::dest, AdcRead::adc_thread_args::device.
Referenced by AsyncADC.
AnalogIn * AdcRead::GetDevice(AdcName name)
Omdanner AdcName enum til pointer til ny AnalogIn object for respektivt ADC ben.
name enum for det ADC ben der skal måles på AnalogIn* pointer til oprettet device
References BAT_I_1, BAT_V_1, MPPT_I_1, MPPT_V_1, SUB_I_1, SUB_V_1.
Referenced by AsyncADC.
static float AdcRead::ReadFloat(AnalogIn *device)
void AdcRead::AsyncADC(int adc_count)
Starter et givent antal threads der hver kører ReadU16() med dets givet ADC ben.
adc_count Antal ADC'er at måle på
References adc_read_list, arg_list, GetDevice, ReadU16, t_adc_read.
Referenced by DoRead.