Fsm
State
Fsm::State Fsm::current_state_
Referenced by DownState, Fsm, GetCurrentState, StateChanger, ToString, UpState.
Fsm::Fsm(State start_state)
References current_state_.
void Fsm::DetermineState(AdcRead::adc_reading reading)
Bedøm en ny target state på baggrund af ADC måling og kald StateChanger()
Batterispændingen bliver sammenlignet med forskællige arbitære spændingsniveauer og en target state bliver besluttet ud fra dette. Herefter betragtes den samlede effekt fra MPPT'erne, og hvis denne ikke overstiger et arbitrært niveau, sænkes target state med 1. Aloritmen er simpel og mest til for at have et eksempel på en algoritme. reading ADC måling at finde ny state på baggrund af.
References AdcRead::adc_reading::bat_v_1, CRIT_MPPT_POW_SUM, EMERGENCY, GetPower, HIGH, LOW, MID, MID_HIGH, MID_LOW, StateChanger, VBAT_EMERGENCY, VBAT_LOW, VBAT_MID, VBAT_MID_HIGH, VBAT_MID_LOW.
Referenced by NewState.
void Fsm::UpState()
Gå en state up. Hvis nuværende state er den højeste, gør intet.
References current_state_, EMERGENCY, HIGH, LOW, MID, MID_HIGH, MID_LOW.
Referenced by StateChanger.
void Fsm::DownState()
Gå en state ned. Hvis nuværende state er den laveste, gør intet.
References current_state_, EMERGENCY, HIGH, LOW, MID, MID_HIGH, MID_LOW.
Referenced by StateChanger.
Fsm::State Fsm::GetCurrentState()
Getter for nuværende state.
Fsm::State
References current_state_.
Referenced by AdcRead::DoRead, PowerManage::UpdateEnabled.
std::string Fsm::ToString()
Giver navnet på nuverende state.
std::string
References current_state_, GetString.
std::string Fsm::GetString(State name)
Omdanner State enum til string.
name state der ønskes navn på std::string String med navnet på staten
References EMERGENCY, HIGH, LOW, MID, MID_HIGH, MID_LOW.
Referenced by ToString.
void Fsm::StateChanger(State target_state)
Incrementer eller decrementer current_state, alt efter om den er lavere eller højere end target_state.
target_state
References current_state_, DownState, UpState.
Referenced by DetermineState.
float Fsm::GetPower(AdcRead::adc_reading reading)
Beregn effekten for alle MPPT'er i en ADC måling.
reading ADC måling for hvilken vi vil finde MMPT effekten float Effekt for samlet MPPT'er i watt
References MPPT_CURR_AMP, AdcRead::adc_reading::mppt_i_1, MPPT_SHUNT_RES, AdcRead::adc_reading::mppt_v_1.
Referenced by DetermineState.