CanCom
CanMessageId
uint8_t CanCom::serialized_buffer_[send_reading_size *ADC_BUFFER_SIZE]
Referenced by GetFrameSize, GetReading, SendBuffer, SendReadings, ShiftBuffer.
NoMutexCAN * CanCom::can_
Referenced by CanCom, SendBuffer.
CanCom::CanCom(NoMutexCAN *can)
References can, can_.
void CanCom::SendBuffer(size_t size)
Sender fra serializeret buffer over CAN ved at dele hvert frame op i 8 bytes.
size Antale bytes at sende fra bufferen
References can_, CAN_GET_READING, LOG, LOG_DEBUG, serialized_buffer_, ShiftBuffer.
Referenced by SendReadings.
void CanCom::SendReadings()
Send alle målinger i CircularBuffer'eren (adc_buffer_) over CAN.
Hver måling i adc_buffer_ enkodes med Google Protobuf structen send_reading og serialiseres. De serialiserede bytes lægges ind i serialized_buffer. Hvis der ikke blev målt på mppt og rails i en given måling sættes has_mppt_x_x og has_sub_x_x bools'ne til False, og protobufs sørger for at serialiseringen fylder mindre.
References AdcRead::adc_buffer_, _send_reading::bat_i_1, _send_reading::bat_v_1, _send_reading::has_mppt_i_1, _send_reading::has_mppt_v_1, _send_reading::has_sub_i_1, _send_reading::has_sub_v_1, _send_reading::mppt_i_1, _send_reading::mppt_v_1, send_reading_fields, SendBuffer, serialized_buffer_, _send_reading::sub_i_1, _send_reading::sub_v_1, _send_reading::timestamp.
Referenced by CanHandler.
AdcRead::adc_reading CanCom::GetReading()
Modtag en enkelt ADC måling fra serialized_buffer_.
AdcRead::adc_reading decoded adc reading Anvdendes ikke da vi ikke modtager ADC målinger igennem CAN
References _send_reading::bat_i_1, _send_reading::bat_v_1, GetFrameSize, _send_reading::has_mppt_v_1, _send_reading::mppt_i_1, _send_reading::mppt_v_1, send_reading_fields, serialized_buffer_, ShiftBuffer, _send_reading::sub_i_1, _send_reading::sub_v_1, _send_reading::timestamp.
size_t CanCom::GetFrameSize()
Find størrelsen af en modtaget Protobuf pakke inden decode.
size_t størrelsen af pakken i bytes Anvdendes ikke da vi ikke modtager pakker der fylder mere end 1 CAN frame
References LOG, LOG_ERROR, send_reading_size, serialized_buffer_.
Referenced by GetReading.
void CanCom::ShiftBuffer(size_t shift_bytes)
Rykker alle bytes i serialized_buffer_ med et antal pladser.
shift_bytes antal pladser at rykke pladser i bufferen
References serialized_buffer_.
Referenced by GetReading, SendBuffer.