PowerManage
Modules
bool PowerManage::enabled_modules_[SUBMODULES_NUM]
Referenced by UpdateEnabled, WriteSubState.
bool PowerManage::module_override_[SUBMODULES_NUM]
Referenced by SetOverride, WriteSubState.
DigitalOut PowerManage::power_rails_[1]
Referenced by OceFromIsr, WriteSubState.
string PowerManage::ToString(Modules module)
Omdanner modul til string med navnet for modulet.
module Det modul der ønskes navn på string med navnet for modulet
References SUB_1.
Referenced by OceIsr::EventHandler.
void PowerManage::OceFromIsr(Modules module)
Høj prioritetet deaktivering af en power rail ved OCE.
module Modulet der blev målt OCE på
References power_rails_.
Referenced by OceIsr::Handle.
void PowerManage::SetOverride(Modules module, bool is_on)
Opdaterer et modul i module_override_ listen. Og Kalder WriteSubState().
module Det modul der skal aktiveres/deaktiveres is_on false = deaktiver | true = aktiver
References module_override_, SUB_1, WriteSubState.
Referenced by OceIsr::EventHandler.
void PowerManage::UpdateEnabled()
Henter den nuværende state fra FSM biblioteket og opdaterer enabled_modules_ listen efter denne. Kalder til sidst WriteSubState().
References Fsm::EMERGENCY, enabled_modules_, Fsm::GetCurrentState, Fsm::HIGH, Fsm::LOW, Fsm::MID, Fsm::MID_HIGH, Fsm::MID_LOW, WriteSubState.
Referenced by Setup, UpdateSubs.
void PowerManage::WriteSubState()
Opdaterer den endelige tisltand af Power Rails ved at AND'e enabled_modules_ og module_override_.
References enabled_modules_, module_override_, power_rails_.
Referenced by SetOverride, UpdateEnabled.