main.cpp
Fsm fsm(FSM_START_STATE)(FSM_START_STATE)
EventQueue IsrQueue
Referenced by OnCanRec, Setup.
EventQueue AdcQueue
Referenced by main.
CanCom cancom & can(CAN_RD_PIN, CAN_TD_PIN, CAN_BITRATE)
Referenced by CanCom::CanCom, main, OnCanRec.
Watchdog& watchdog
Referenced by StartWatchdog, UpdateSubs.
CANMessage can_time_sync
Referenced by CanTimeSync, OnCanRec.
CANMessage can_req
Referenced by OnCanRec.
Ticker adc_ticker
Referenced by main.
Mail<AdcRead::adc_reading, 8> adc_mail
Referenced by NewState, ReadAdc.
bool can_time_isr
Referenced by CanHandler, OnCanRec.
bool can_req_isr
Referenced by CanHandler, OnCanRec.
Thread t_can_handler(osPriorityNormal, OS_STACK_SIZE, nullptr,"CAN Handler")
Thread t_ISR_handler(osPriorityISR, 1024, nullptr, "OCE Handler")
Referenced by Setup.
Thread t_adc_main(osPriorityNormal, 1024, nullptr,"ADC Handler")
Referenced by main.
Thread t_state_subs(osPriorityNormal, 1024, nullptr,"State Updater")
Referenced by main.
OceIsr oce1(OCE_1_PIN, &IsrQueue, PowerManage::SUB_1)
void ReadAdc()
Sætter ADC måling igang. Kører hvert 5. sekundt med mindre en vigtigere thread pre-empt'er den. Lægger den nye måling i kø til NewState()
References adc_mail, AdcRead::DoRead, LOG, LOG_DEBUG.
Referenced by main.
void UpdateSubs()
Opdaterer de aktiverede moduler på baggrund af ny state og kicker watchdog.
References LOG, LOG_DEBUG, PowerManage::UpdateEnabled, watchdog.
Referenced by NewState.
void StartWatchdog()
Starter Watchdog hvis timeout er for langt sættes den istedet til den længste tilladte værdi.
References LOG, LOG_DEBUG, LOG_WARNING, watchdog, WATCHDOG_TIMEOUT.
Referenced by Setup.
void CanTimeSync()
ISR deferred handler for at decode time sync package og opdatere RTC med den modtagede værdi.
References can_time_sync, _time_sync::current_time, time_sync_fields.
Referenced by CanHandler.
void CanHandler()
ISR deferred handler der reagerer på flag fra OnCanRec()
Lettere overflødig og lævn fra tidligere metode uden brug af EventQueue
References can_req_isr, can_time_isr, CanTimeSync, LOG, LOG_DEBUG, CanCom::SendReadings.
Referenced by OnCanRec.
void OnCanRec()
ISR deferred handler til at beslutte handling på baggrund af CAN framets ID.
References can, CanCom::CAN_GET_READING, can_req, can_req_isr, can_time_isr, CanCom::CAN_TIME_SYNC, can_time_sync, CanHandler, IsrQueue.
Referenced by main.
void Setup()
Køres en enkelt gang når systemet starter.
References IsrQueue, LOG_LEVEL, Log::reporting_level_, Log::serial_, StartWatchdog, t_ISR_handler, PowerManage::UpdateEnabled.
Referenced by main.
void NewState()
Modtager ny måling fra ReadAdc() og bestemmer ny state på baggrund af disse data.
References adc_mail, Fsm::DetermineState, LOG, LOG_DEBUG, UpdateSubs.
Referenced by main.
int main()
Sætter threads igang og sover.
int standard
References adc_ticker, AdcQueue, can, LOG, LOG_INFO, NewState, OnCanRec, ReadAdc, Setup, t_adc_main, t_state_subs.