.TH "_send_reading" 3 "Tue May 17 2022" "EPS MCU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_send_reading
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reading\&.pb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBbat_v_1\fP"
.br
.ti -1c
.RI "uint32_t \fBbat_i_1\fP"
.br
.ti -1c
.RI "bool \fBhas_mppt_v_1\fP"
.br
.ti -1c
.RI "uint32_t \fBmppt_v_1\fP"
.br
.ti -1c
.RI "bool \fBhas_mppt_i_1\fP"
.br
.ti -1c
.RI "uint32_t \fBmppt_i_1\fP"
.br
.ti -1c
.RI "bool \fBhas_sub_v_1\fP"
.br
.ti -1c
.RI "uint32_t \fBsub_v_1\fP"
.br
.ti -1c
.RI "bool \fBhas_sub_i_1\fP"
.br
.ti -1c
.RI "uint32_t \fBsub_i_1\fP"
.br
.ti -1c
.RI "uint64_t \fBtimestamp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint32_t _send_reading::bat_i_1"

.SS "uint32_t _send_reading::bat_v_1"

.SS "bool _send_reading::has_mppt_i_1"

.SS "bool _send_reading::has_mppt_v_1"

.SS "bool _send_reading::has_sub_i_1"

.SS "bool _send_reading::has_sub_v_1"

.SS "uint32_t _send_reading::mppt_i_1"

.SS "uint32_t _send_reading::mppt_v_1"

.SS "uint32_t _send_reading::sub_i_1"

.SS "uint32_t _send_reading::sub_v_1"

.SS "uint64_t _send_reading::timestamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for EPS MCU from the source code\&.
