.TH "_time_sync" 3 "Tue May 17 2022" "Firmware for EPS MCU on AAUSAT6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_time_sync
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reading\&.pb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBcurrent_time\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint64_t _time_sync::current_time"


.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware for EPS MCU on AAUSAT6 from the source code\&.
