.TH "AdcRead::adc_reading" 3 "Tue May 17 2022" "EPS MCU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdcRead::adc_reading
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AdcRead\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBbat_v_1\fP"
.br
.ti -1c
.RI "uint16_t \fBbat_i_1\fP"
.br
.ti -1c
.RI "uint16_t \fBmppt_v_1\fP"
.br
.ti -1c
.RI "uint16_t \fBmppt_i_1\fP"
.br
.ti -1c
.RI "uint16_t \fBsub_v_1\fP"
.br
.ti -1c
.RI "uint16_t \fBsub_i_1\fP"
.br
.ti -1c
.RI "time_t \fBtimestamp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint16_t AdcRead::adc_reading::bat_i_1"

.SS "uint16_t AdcRead::adc_reading::bat_v_1"

.SS "uint16_t AdcRead::adc_reading::mppt_i_1"

.SS "uint16_t AdcRead::adc_reading::mppt_v_1"

.SS "uint16_t AdcRead::adc_reading::sub_i_1"

.SS "uint16_t AdcRead::adc_reading::sub_v_1"

.SS "time_t AdcRead::adc_reading::timestamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for EPS MCU from the source code\&.
