.TH "AdcRead::adc_thread_args" 3 "Tue May 17 2022" "Firmware for EPS MCU on AAUSAT6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdcRead::adc_thread_args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AdcRead\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AnalogIn * \fBdevice\fP"
.br
.ti -1c
.RI "uint16_t * \fBdest\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint16_t* AdcRead::adc_thread_args::dest"

.SS "AnalogIn* AdcRead::adc_thread_args::device"


.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware for EPS MCU on AAUSAT6 from the source code\&.
