.TH "lib/FSM/Fsm.h" 3 "Tue May 17 2022" "EPS MCU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/FSM/Fsm.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'ProjectConfig\&.h'\fP
.br
\fC#include 'AdcRead\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFsm\fP"
.br
.RI "Finite State Machine class der håndterer nuverende state og ændring af denne\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EPS MCU from the source code\&.
