.TH "lib/NVStore/NVStore.cpp" 3 "Tue May 17 2022" "EPS MCU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/NVStore/NVStore.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'NVStore\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "FlashIAPBlockDevice \fBbd\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "TDBStore nvStore & bd"

.SH "Author"
.PP 
Generated automatically by Doxygen for EPS MCU from the source code\&.
