.TH "lib/PowerManage/PowerManage.h" 3 "Tue May 17 2022" "EPS MCU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/PowerManage/PowerManage.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <Fsm\&.h>\fP
.br
\fC#include 'ProjectConfig\&.h'\fP
.br
\fC#include 'AdcRead\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPowerManage\fP"
.br
.RI "Aktivering og deaktivering af powerrails på baggrund af OCE og state\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EPS MCU from the source code\&.
