.TH "lib/Config/ProjectConfig.h" 3 "Tue May 17 2022" "EPS MCU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Config/ProjectConfig.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC_MEASURE_LOOPS\fP   5"
.br
.ti -1c
.RI "#define \fBADC_BUFFER_SIZE\fP   100"
.br
.ti -1c
.RI "#define \fBVBAT_MID_HIGH\fP   4\&.0f"
.br
.ti -1c
.RI "#define \fBVBAT_MID\fP   3\&.7f"
.br
.ti -1c
.RI "#define \fBVBAT_MID_LOW\fP   3\&.4f"
.br
.ti -1c
.RI "#define \fBVBAT_LOW\fP   3\&.2f"
.br
.ti -1c
.RI "#define \fBVBAT_EMERGENCY\fP   3\&.0f"
.br
.ti -1c
.RI "#define \fBMPPT_CURR_AMP\fP   200\&.0f"
.br
.ti -1c
.RI "#define \fBMPPT_SHUNT_RES\fP   0\&.02f"
.br
.ti -1c
.RI "#define \fBCAN_BITRATE\fP   5e5"
.br
.ti -1c
.RI "#define \fBWATCHDOG_TIMEOUT\fP   10000"
.br
.ti -1c
.RI "#define \fBFSM_START_STATE\fP   \fBFsm::MID\fP"
.br
.ti -1c
.RI "#define \fBCRIT_MPPT_POW_SUM\fP   1\&.0f"
.br
.ti -1c
.RI "#define \fBLOG_LEVEL\fP   \fBLOG_DEBUG\fP"
.br
.ti -1c
.RI "#define \fBLOG_COM_TYPE\fP   SERIAL"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_BUFFER_SIZE   100"

.SS "#define ADC_MEASURE_LOOPS   5"

.SS "#define CAN_BITRATE   5e5"

.SS "#define CRIT_MPPT_POW_SUM   1\&.0f"

.SS "#define FSM_START_STATE   \fBFsm::MID\fP"

.SS "#define LOG_COM_TYPE   SERIAL"

.SS "#define LOG_LEVEL   \fBLOG_DEBUG\fP"

.SS "#define MPPT_CURR_AMP   200\&.0f"

.SS "#define MPPT_SHUNT_RES   0\&.02f"

.SS "#define VBAT_EMERGENCY   3\&.0f"

.SS "#define VBAT_LOW   3\&.2f"

.SS "#define VBAT_MID   3\&.7f"

.SS "#define VBAT_MID_HIGH   4\&.0f"

.SS "#define VBAT_MID_LOW   3\&.4f"

.SS "#define WATCHDOG_TIMEOUT   10000"

.SH "Author"
.PP 
Generated automatically by Doxygen for EPS MCU from the source code\&.
