/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "reading.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(send_reading, send_reading, AUTO)


PB_BIND(time_sync, time_sync, AUTO)



