/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_READING_PB_H_INCLUDED
#define PB_READING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _send_reading { 
    uint32_t bat_v_1; 
    uint32_t bat_i_1; 
    bool has_mppt_v_1;
    uint32_t mppt_v_1; 
    bool has_mppt_i_1;
    uint32_t mppt_i_1; 
    bool has_sub_v_1;
    uint32_t sub_v_1; 
    bool has_sub_i_1;
    uint32_t sub_i_1; 
    uint64_t timestamp; 
} send_reading;

typedef struct _time_sync { 
    uint64_t current_time; 
} time_sync;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define send_reading_init_default                {0, 0, false, 0, false, 0, false, 0, false, 0, 0}
#define time_sync_init_default                   {0}
#define send_reading_init_zero                   {0, 0, false, 0, false, 0, false, 0, false, 0, 0}
#define time_sync_init_zero                      {0}

/* Field tags (for use in manual encoding/decoding) */
#define send_reading_bat_v_1_tag                 1
#define send_reading_bat_i_1_tag                 2
#define send_reading_mppt_v_1_tag                3
#define send_reading_mppt_i_1_tag                4
#define send_reading_sub_v_1_tag                 5
#define send_reading_sub_i_1_tag                 6
#define send_reading_timestamp_tag               7
#define time_sync_current_time_tag               1

/* Struct field encoding specification for nanopb */
#define send_reading_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   bat_v_1,           1) \
X(a, STATIC,   REQUIRED, UINT32,   bat_i_1,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   mppt_v_1,          3) \
X(a, STATIC,   OPTIONAL, UINT32,   mppt_i_1,          4) \
X(a, STATIC,   OPTIONAL, UINT32,   sub_v_1,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   sub_i_1,           6) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         7)
#define send_reading_CALLBACK NULL
#define send_reading_DEFAULT NULL

#define time_sync_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   current_time,      1)
#define time_sync_CALLBACK NULL
#define time_sync_DEFAULT NULL

extern const pb_msgdesc_t send_reading_msg;
extern const pb_msgdesc_t time_sync_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define send_reading_fields &send_reading_msg
#define time_sync_fields &time_sync_msg

/* Maximum encoded size of messages (where known) */
#define send_reading_size                        47
#define time_sync_size                           11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
